services:
  influxdb:
    container_name: influxdb
    image: influxdb:2.7-alpine
    volumes:
      - influxdb-data:/var/lib/influxdb2
      - influxdb-config:/etc/influxdb2
    networks:
      - frontend
      - backend
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=julian
      - DOCKER_INFLUXDB_INIT_PASSWORD=growguard
      - DOCKER_INFLUXDB_INIT_ORG=GrowGuard
      - DOCKER_INFLUXDB_INIT_BUCKET=growguard
    restart: always

volumes:
  influxdb-data:
  influxdb-config:

networks:
  frontend:
  backend:
